require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Opay' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  target 'OpayTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

end

target 'Opay-tvOS' do
  # Pods for Opay-tvOS

  target 'Opay-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
